[package]
name = "futures-timer"
version = "2.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rustasync/futures-timer"
homepage = "https://github.com/rustasync/futures-timer"
documentation = "https://docs.rs/futures-timer"
description = """
Timeouts and intervals for futures.
"""

[dependencies]
pin-utils = "0.1.0-alpha.4"

[dev-dependencies]
futures = "0.3.0"
runtime = "0.3.0-alpha.8"
